sudo: required
services:
    - docker

before_install:
    - docker build -t vincefb112/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vincefb112/react-test npm run test

after_success:
  - docker build -t vincefb112/multi-client ./client
  - docker build -t vincefb112/multi-nginx ./nginx
  - docker build -t vincefb112/multi-server ./server
  - docker build -t vincefb112/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vincefb112/multi-client
  - docker push vincefb112/multi-nginx
  - docker push vincefb112/multi-server
  - docker push vincefb112/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-572060515853
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY